version: '3.8'

services:
  # Serviço de banco de dados para o projeto clinicasa
  database:
    image: postgres:15
    container_name: clinicasa-postgres-container
    restart: always
    environment:
      # Lendo as credenciais do arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Lendo a porta do arquivo .env
      - "${DB_PORT}:5432"
    volumes:
      - clinicasa-db-volume:/var/lib/postgresql/data

volumes:
  # Definindo o volume que guardará os dados do banco
  clinicasa-db-volume: